---
# ansible-galaxy collection install -r requirements.yml
collections:
  - name: community.general      # nmcli (WiFi), misc modules
  - name: ansible.posix          # optional (synchronize, mount helpers)
